"""Validation suite for step_import.py (docs/meshing_module_plan.md
Section 6.3, "step_import.py").

fixtures/unit_cube.step is authored directly in a text editor (ISO
10303-21 / STEP AP214, hand-written B-rep: 8 vertices, 12 edges, 6 planar
faces, one closed shell, one manifold solid brep -- not generated by this
project's own code) as a cube with raw coordinates spanning 0 to 1 on each
axis. Its known, hand-computed volume is 1 (cubic unit) -- the whole point
of this test is to check that "cubic unit" gets correctly interpreted as
either 1 m^3 or 1e-9 m^3 depending on the caller-supplied `length_unit`,
per Section 0.5.
"""
from pathlib import Path

import pytest

from meshing.step_import import StepUnitAmbiguityError, import_step

FIXTURE = Path(__file__).parent / "fixtures" / "unit_cube.step"


def _occ_volume(dim_tag: tuple[int, int]) -> float:
    import gmsh

    return gmsh.model.occ.getMass(*dim_tag)  # type: ignore[no-any-return]


def test_import_as_meters(gmsh_model):
    dim_tags = import_step(FIXTURE, length_unit="m")
    assert len(dim_tags) == 1
    assert _occ_volume(dim_tags[0]) == pytest.approx(1.0, rel=1e-6)


def test_import_as_millimeters(gmsh_model):
    dim_tags = import_step(FIXTURE, length_unit="mm")
    assert len(dim_tags) == 1
    assert _occ_volume(dim_tags[0]) == pytest.approx(1e-9, rel=1e-6)


def test_import_as_centimeters(gmsh_model):
    dim_tags = import_step(FIXTURE, length_unit="cm")
    assert len(dim_tags) == 1
    assert _occ_volume(dim_tags[0]) == pytest.approx(1e-6, rel=1e-6)


def test_missing_length_unit_raises_step_unit_ambiguity_error(gmsh_model):
    with pytest.raises(StepUnitAmbiguityError):
        import_step(FIXTURE, length_unit=None)


def test_unknown_length_unit_raises_value_error(gmsh_model):
    with pytest.raises(ValueError):
        import_step(FIXTURE, length_unit="furlong")

    # Note: this module's docstring documents an empirically-verified Gmsh
    # quirk -- its own un-overridden Geometry.OCCTargetUnit default silently
    # rescales imported STEP geometry by 1000x, in a *fresh* interpreter.
    # That specific behavior isn't re-demonstrated as its own test here:
    # Geometry.OCCTargetUnit turns out to be process-global state that
    # outlives gmsh.initialize()/finalize() and doesn't cleanly reset to its
    # true virgin default via gmsh.option.setString once anything in this
    # process has set it, which would make a test asserting that "default"
    # value order-dependent on whatever ran earlier in the same session --
    # exactly the kind of hazard worth avoiding rather than demonstrating.
